.catalog:
  name: "php5"
  version: "v0.1-php5"
  description: "PHP5 runtime for Lambda"
  minimum_rancher_version: "v1.0.1"
  questions:
    - variable: webroot_volume_name
      description: "e.g volume_name"
      label: "Webroot shared volume name"
      required: true
      type: "string"
    - variable: webroot
      description: "Change the default webroot directory from '/var/www/html' to your own setting"
      label: "Webroot"
      default: "/var/www/html"
      required: true
      type: "string"
    - variable: git_repo
      description: "URL to the repository containing your source code. If you are using a personal token, this is the https URL without https://, e.g github.com/project/ for ssh prepend with git@ e.g git@github.com:project.git"
      label: "Git Repo"
      required: false
      type: "string"
    - variable: git_branch
      description: "Select a specific branch (optional)"
      label: "Git Branch"
      required: false
      type: "string"
    - variable: git_email
      label: "Git Email"
      description: "Set your email for code pushing (required for git to work)"
      required: false
      type: "string"
    - variable: git_name
      label: "Git Name"
      description: "Set your name for code pushing (required for git to work)"
      required: false
      type: "string"
    - variable: ssh_key
      label: "SSH Key"
      description: "Private SSH deploy key for your repository base64 encoded (requires write permissions for pushing)"
      required: false
      type: "string"
    - variable: git_personal_token
      label: "Git Personal Token"
      description: "Personal access token for your git account (required for HTTPS git access)"
      required: false
      type: "string"
    - variable: git_username
      label: "Git Username"
      description: "Git username for use with personal tokens. (required for HTTPS git access)"
      required: false
      type: "string"
    - variable: errors
      label: "Errors Settings"
      description: "Set to 1 to display PHP Errors in the browser"
      default: "1"
      required: true
      type: "enum"
      options:
        - "0"
        - "1"
    - variable: hide_nginx_headers
      label: "Hide Nginx Headers"
      description: "Disable by setting to 0, default behaviour is to hide nginx + php version in headers"
      default: "1"
      required: true
      type: "enum"
      options:
        - "0"
        - "1"
    - variable: php_mem_limit
      label: "PHP Memory Limit"
      description: "Set higher PHP memory limit, default is 128M"
      default: "128M"
      required: true
      type: "enum"
      options:
        - "64M"
        - "128M"
        - "256M"
    - variable: php_post_max_size
      label: "PHP Post Max Size"
      description: "Set a larger post_max_size, default is 100M"
      default: "100M"
      required: true
      type: "enum"
      options:
        - "2M"
        - "10M"
        - "100M"
        - "200M"
    - variable: php_upload_max_filesize
      label: "PHP Upload Max Filesize"
      description: "Set a larger upload_max_filesize, default is 100M"
      default: "100M"
      required: true
      type: "enum"
      options:
        - "2M"
        - "10M"
        - "100M"
        - "200M"
    - variable: run_scripts
      label: "Run Scripts Settings"
      description: "Set to 1 to execute scripts"
      default: "1"
      required: true
      type: "enum"
      options:
        - "0"
        - "1"
runtime:
  scale: 1
  health_check:
    port: 80
    interval: 2000
    initializing_timeout: 60000
    unhealthy_threshold: 3
    strategy: recreate
    healthy_threshold: 2
    response_timeout: 2000
